from . import res_partner
from . import hr_employee
from . import fund_management_meeting_minutes_type
from . import fund_management_meeting_minutes
from . import fund_management_category
from . import fund_management_approval_stage
from . import fund_management_approval_detail
from . import fund_management_fund_type
from . import fund_management_procurement_method
from . import fund_management_payment_method
from . import fund_management
