from . import hr_employee
from . import res_partner
from . import contract_expense_payment_method
from . import contract_expense_procurement_method
from . import contract_expense_fund_type
from . import contract_expense_category
from . import contract_expense_approval_stage
from . import contract_expense_approval_detail
from . import contract_expense_attachment
from . import contract_expense_overdue
from . import contract_expense
